### ISSUE TITLE
pushy-client service issue. Windows platform.

### ISSUE THREAD

**Issue by fog1985** [chef/chef-push#2]
Hi guys,

I have found an issue with pushy-client service for windows.
It happenes when it just hangs and becomes unresponseve. 
Eventhough it stays in running state among services. 
The only thing fixes it and makes available. Service restart.

Can you please take a look into and add some kind of self-check if it's working (listening)) or not. 

For last two weeks it hang on around 10 boxes out of 15 where it was installed. 
So I had to log into each box and restart service. 

Thank you in advance. 
Regards,
Taras.

**Comment by markan** [comment]
Thanks for reporting this. I'm in the process of improving the push client on windows and this is helpful to know.

I think what you are proposing is to have the windows service monitor the actual push client running and reset it when it becomes non-responsive; that seems sensible, but I'd also like to understand why it's hanging in the first place.

Can you give me any tips on how to make it hang? I assume by hang, you mean stops responding to server commands. I guess a hang involves a full freeze, including heartbeats to the server. Does a client hang even if no jobs have been run on it? Anything show up in the client logs when it hangs? 

Does the server think the client is available when it's frozen?

**Comment by fog1985** [comment]
Hi Mark, 
When it was hang on the system it still was being shown as in running state.  But if I was doing "knife node status <node name>" I was getting "unavailable" state.  So it was not responding at all. But for some reason state on client side was being shown as running. 
Unfortunately I don't remember boxes names where this issue happened.  
If I see it again I will let you know.  
please let me know what logs I should copy and send to you once I find this issue again. 
Regards, Taras. 

20 лютого 2015, 00:04:04, від Mark Anderson < notifications@github.com >: 

Thanks for reporting this I'm in the process of improving the push client on windows and this is helpful to know. I think what you are proposing is to have the windows service monitor the actual push client running and reset it when it becomes non-responsive; that seems sensible, but I'd also like to understand why it's hanging in the first place. Can you give me any tips on how to make it hang? I assume by hang, you mean stops responding to server commands. I guess a hang involves a full freeze, including heartbeats to the server. Does a client hang even if no jobs have been run on it? Anything show up in the client logs when it hangs? Does the server think the client is available when it's frozen? —

**Comment by fog1985** [comment]
Hi Mark, 
I have got the same issue.  And it's actually happening all the time.  I have even developed automated powershell script to monitor pushy-client responsiveness and let me know once node is unavailable within pushy-client.   
I have around few nodes each day where pushy-client becomes unresponsive.  
Please check attachment of the logs from one of the nodes. 
Here is some details from node: chef-client version: 12.0.0, 12.1.0, 11.16.4. So actually it happens on different chef-client versions. Pushy-client version is in attachment. How to resolve: just restart windows service pushy-client.  How visible: from system none. It's in running state etc. Only "knife node status <node name>" to see if it's available or unavailable. Windows version: 2008 R2. 64-bits 
Thank you in advance for the help. 
Regards, Taras. 

20 лютого 2015, 00:04:04, від Mark Anderson < notifications@github.com >: 

Thanks for reporting this I'm in the process of improving the push client on windows and this is helpful to know. I think what you are proposing is to have the windows service monitor the actual push client running and reset it when it becomes non-responsive; that seems sensible, but I'd also like to understand why it's hanging in the first place. Can you give me any tips on how to make it hang? I assume by hang, you mean stops responding to server commands. I guess a hang involves a full freeze, including heartbeats to the server. Does a client hang even if no jobs have been run on it? Anything show up in the client logs when it hangs? Does the server think the client is available when it's frozen? —

**Comment by glasschef** [comment]
From ticket 3349, it looks like the heartbeat fails and then things get bad:

```
[2015-03-30T16:06:58+00:00] DEBUG: [fqdn] Received server heartbeat (sequence #5780913)
[2015-03-30T16:06:58+00:00] DEBUG: [fqdn] Sending heartbeat (sequence #533971)
[2015-03-30T16:06:59+00:00] DEBUG: [fqdn] Sending heartbeat (sequence #533972)
[2015-03-30T16:07:00+00:00] DEBUG: [fqdn] Sending heartbeat (sequence #533973)
[2015-03-30T16:07:01+00:00] DEBUG: [fqdn] Sending heartbeat (sequence #533974)
[2015-03-30T16:07:02+00:00] INFO: [fqdn] Server has missed 4 heartbeats in a row.  Considering it offline, and stopping heartbeat.
[2015-03-30T16:07:02+00:00] INFO: [fqdn] Closing and reopening sockets since server is down ...
[2015-03-30T16:07:03+00:00] INFO: [fqdn] Stopping command / server heartbeat receive thread and destroying sockets ...
[2015-03-30T16:07:03+00:00] INFO: [fqdn] Connecting to command channel at tcp://ip-numbers-here.ec2.internal:10002
[2015-03-30T16:07:15+00:00] ERROR: [fqdn] Error reconfiguring sockets when server went down: Invalid argument
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:106:in `connect'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:106:in `start'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:133:in `block (2 levels) in reconfigure'
<internal:prelude>:10:in `synchronize'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:131:in `block in reconfigure'
<internal:prelude>:10:in `synchronize'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:130:in `reconfigure'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:57:in `block (2 levels) in initialize'
c:/opscode/pushy/embedded/lib/ruby/1.9.1/win32ole.rb:13:in `call'
c:/opscode/pushy/embedded/lib/ruby/1.9.1/win32ole.rb:13:in `block in initialize'
...
[2015-03-30T17:48:56+00:00] INFO: [fqdn] Config is now 3600 seconds old.  Reconfiguring / reloading keys ...
[2015-03-30T17:48:56+00:00] INFO: [fqdn] Reconfiguring client / reloading keys ...
...
[2015-03-30T17:48:57+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
[2015-03-30T17:48:57+00:00] INFO: [fqdn] Stopping command / server heartbeat receive thread and destroying sockets ...
[2015-03-30T17:48:57+00:00] ERROR: [fqdn] Error reconfiguring: undefined method `close' for nil:NilClass
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:176:in `internal_stop'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:132:in `block (2 levels) in reconfigure'
<internal:prelude>:10:in `synchronize'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:131:in `block in reconfigure'
<internal:prelude>:10:in `synchronize'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:130:in `reconfigure'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:100:in `block in reconfigure'
<internal:prelude>:10:in `synchronize'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:94:in `reconfigure'
c:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:113:in `block in trigger_reconfigure'
c:/opscode/pushy/embedded/lib/ruby/1.9.1/win32ole.rb:13:in `call'
c:/opscode/pushy/embedded/lib/ruby/1.9.1/win32ole.rb:13:in `block in initialize'
```

The reconfigure attempts will keep crashing with `undefined method 'close' for nil:NilClass`

**Comment by ghost** [comment]
can this bug be fixed? 

if you format a node of a target node and reinstall os, then this bug ocurrs. 

please fix this..

**Comment by docwho76** [comment]
Can confirm that this bug SUCKS big time. Can we get some love on this, you guys are killin me smalls.

**Comment by thehar** [comment]
Bumping this as I'm also encountering this issue.

**Comment by TuranTimur** [comment]
I wouldn't recommend chef-push for production because of this bug. A lot of our team members were exhausted with this, and I was the guy who is to blame because I trusted chef-push.

**Comment by KineticHub** [comment]
I'm also bumping this issue, Windows 10 with Chef Pushy Client v1.1.5

**Comment by justmiles** [comment]
I'm seeing this error as well, but with a CentOS box. It might not be confined to just Windows. Restarting the service temporarily fixes it, but it does eventually become unresponsive after the heartbeat stops.

```
2016-03-01_12:35:20.66887 INFO: [fqdn] Config is now 3600 seconds old.  Reconfiguring / reloading keys ...
2016-03-01_12:35:20.66897 INFO: [fqdn] Reconfiguring client / reloading keys ...
2016-03-01_12:35:20.66897 INFO: [fqdn] Retrieving configuration from https://chef-fqdn/organizations/edo/pushy/config/fqdn ...
2016-03-01_12:35:20.70034 INFO: [fqdn] Stopping command / server heartbeat receive thread and destroying sockets ...
2016-03-01_12:35:20.70036 ERROR: [fqdn] Error reconfiguring: undefined method `close' for nil:NilClass
2016-03-01_12:35:20.70036 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:176:in `internal_stop'
2016-03-01_12:35:20.70037 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:132:in `block (2 levels) in reconfigure'
2016-03-01_12:35:20.70037 <internal:prelude>:10:in `synchronize'
2016-03-01_12:35:20.70037 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:131:in `block in reconfigure'
2016-03-01_12:35:20.70037 <internal:prelude>:10:in `synchronize'
2016-03-01_12:35:20.70038 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:130:in `reconfigure'
2016-03-01_12:35:20.70038 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:100:in `block in reconfigure'
2016-03-01_12:35:20.70039 <internal:prelude>:10:in `synchronize'
2016-03-01_12:35:20.70039 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:94:in `reconfigure'
2016-03-01_12:35:20.70039 /opt/opscode-push-jobs-client/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:113:in `block in trigger_reconfigure'
```

Same error: `Error reconfiguring: undefined method 'close' for nil:NilClass`
chef-client 12.5.1

**Comment by talcloudshare** [comment]
Any updates on this issue? I'm experiencing issues with Push Jobs Client on my Windows nodes - nodes report to be unavailable, and Push Jobs Client service should be restarted in order to get them to be available again

**Comment by SaiduluAlli** [comment]
Any updates yet....

**Comment by docwho76** [comment]
Can push jobs PLEASE get some love. This is ridic

**Comment by tphan1994** [comment]
Hello all,

We encountered this same issue last week, why does Push Jobs Client service has to be restarted for node to become "available"?

Any fix?

Thank you.

**Comment by sunilkumar452** [comment]
I have  a short fix for this. Start the service without logging into the machine using below command
 
sc \\machine_ip start push-jobs-client

Note; There is double slahes

**Comment by amarkulis** [comment]
@sunilkumar452 That fix doesn't apply because the Push Job service stays started in many cases it's just not actually functional.

**Comment by smastrorocco** [comment]
We see the same issue, which causes Chef Automate delivery phases to fail until the service is bounced.  Both Windows and Linux. Only fix we've found is to restart the service.  Additionally, we have a ton of problems with the push client in Test Kitchen, where it will intermittently just fail to restart the push client service, and fail the kitchen run.

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
