### ISSUE TITLE
Exception raised while waiting for job to complete: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by angelosanramon** [chef/chef-push#21]
I have the following whitelist defined:
```
whitelist({"reload_hubot"=>"su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop'"})
```

When I ran knife job start without --capture parameter, the job runs successfully. But when I ran knife job start with --capture parameter, the job keeps running indefinitely. I had to ctrl+c to stop it.

The push-jobs-client.log shows the following:
```
INFO: [UNKNOWN] Job UNKNOWN: whitelist 'reload_hubot' to 'su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop''
INFO: [UNKNOWN] Job UNKNOWN: whitelist 'reload_hubot' to 'su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop''
INFO: [UNKNOWN] Job UNKNOWN: whitelist 'reload_hubot' to 'su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop''
INFO: [zis-hubot-server-ci-01.openstacklocal] Received commit 32dc271a579eba3aeb06e601eaf01735
INFO: [zis-hubot-server-ci-01.openstacklocal] Received run 32dc271a579eba3aeb06e601eaf01735
INFO: [UNKNOWN] Job UNKNOWN: whitelist 'reload_hubot' to 'su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop''
INFO: [UNKNOWN] Job UNKNOWN: whitelist 'reload_hubot' to 'su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop''
INFO: [zis-hubot-server-ci-01.openstacklocal] Job 32dc271a579eba3aeb06e601eaf01735: started command 'su - hubot -c 'npm install git+https://e72e16c7e42f292c6912e7710c838347ae178b4a@github.company.com/zis/some-repo.git#develop'' with PID ''
INFO: [zis-hubot-server-ci-01.openstacklocal] Job 32dc271a579eba3aeb06e601eaf01735 completed with exit code 0
ERROR: [zis-hubot-server-ci-01.openstacklocal] Exception raised while waiting for job 32dc271a579eba3aeb06e601eaf01735 to complete: "\xE2" from ASCII-8BIT to UTF-8
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:224:in `encode'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:224:in `generate'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:224:in `generate'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/protocol_handler.rb:474:in `block in send_signed_json_command'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/protocol_handler.rb:471:in `synchronize'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/protocol_handler.rb:471:in `send_signed_json_command'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/protocol_handler.rb:210:in `send_command'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client.rb:174:in `send_command'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/job_runner.rb:200:in `block in completed'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/job_runner.rb:193:in `synchronize'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/job_runner.rb:193:in `completed'
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.4.8/lib/pushy_client/job_runner.rb:247:in `block in start_process'
INFO: [zis-hubot-server-ci-01.openstacklocal] Received abort
```

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
